spring:
  datasource:
    url: "jdbc:postgresql://${METER_READINGS_DB_HOST_NAME}:${METER_READINGS_DB_PORT}/${METER_READINGS_DB_NAME}"
    username: "${METER_READINGS_DB_USER_NAME}"
    password: "${METER_READINGS_DB_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true