apiVersion: apps/v1
kind: Deployment
metadata:
  name: meter-readings-deployment
  namespace: meter-readings
  labels:
    app: meter-readings
spec:
  selector:
    matchLabels:
      app: meter-readings
  template:
    metadata:
      labels:
        app: meter-readings
    spec:
      containers:
        - name: meter-readings
          image: sebcibaric/meter-readings:latest
          env:
            - name: METER_READINGS_DB_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: meter-readings-db-host-name
                  key: METER_READINGS_DB_HOST_NAME
            - name: METER_READINGS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: meter-readings-db-port
                  key: METER_READINGS_DB_PORT
            - name: METER_READINGS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: meter-readings-db-name
                  key: METER_READINGS_DB_NAME
            - name: METER_READINGS_DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: meter-readings-db-user-name
                  key: METER_READINGS_DB_USER_NAME
            - name: METER_READINGS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meter-readings-db-password
                  key: METER_READINGS_DB_PASSWORD
          ports:
            - containerPort: 8080