create table client (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table address (
    id bigint generated by default as identity,
    city varchar(255) not null,
    house_no varchar(255) not null,
    street varchar(255) not null,
    client_id bigint not null,
    primary key (id),
    constraint ADRESS_UC unique (street, house_no, city),
    constraint UK_ADDRESS_CLIENT_ID unique (client_id),
    constraint FK_ADDRESS_CLIENT_ID
       foreign key (client_id)
       references client
);

create table meter (
    id bigint generated by default as identity,
    client_id bigint not null,
    primary key (id),
    constraint UK_METER_CLIENT_ID unique (client_id),
    constraint FK_METER_CLIENT_ID
       foreign key (client_id)
       references client
);

create table meter_reading (
    id bigint generated by default as identity,
    energy_consumed integer not null,
    month integer not null,
    year integer not null,
    meter_id bigint not null,
    primary key (id),
    constraint FK_METER_READING_METER_ID
       foreign key (meter_id)
       references meter
);