name: Deploy to Kubernetes

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    outputs:
      short_sha: ${{ steps.set_short_sha.outputs.short_sha }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          version: 'latest'
          distribution: 'graalvm'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -Pnative native:compile

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting value in SHORT_SHA variable
        id: set_short_sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.native
          push: true
          tags: sebcibaric/meter-readings:${{ steps.set_short_sha.outputs.short_sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - uses: Azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v4
        with:
          namespace: meter-readings
          action: deploy
          manifests: |
            .manifests/namespace.yml
            .manifests/deployment.yml
            .manifests/service.yml
            .manifests/ingress.yml
          images: |
            docker.io/sebcibaric/meter-readings:${{ needs.build.outputs.short_sha }}