kind: Service
apiVersion: v1
metadata:
  name: meter-readings-service
  namespace: meter-readings
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: meter-readings